# Generated by Django 3.0.5 on 2020-06-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1_rate', models.IntegerField()),
                ('day2_rate', models.IntegerField()),
                ('day3_rate', models.IntegerField()),
                ('day1_count', models.IntegerField(blank=True, default=0, null=True)),
                ('day2_count', models.IntegerField(blank=True, default=0, null=True)),
                ('day3_count', models.IntegerField(blank=True, default=0, null=True)),
                ('advance', models.IntegerField(blank=True, default=0, null=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Employee')),
            ],
        ),
    ]
