# Generated by Django 3.0.5 on 2020-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='year',
            field=models.CharField(default=2020, max_length=10),
            preserve_default=False,
        ),
    ]
