# Generated by Django 3.0.5 on 2020-07-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-id']},
        ),
    ]
