# Generated by Django 3.0.5 on 2020-07-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0002_auto_20200625_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
    ]
