# Generated by Django 3.0.5 on 2020-07-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
