# Generated by Django 3.0.5 on 2021-05-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210417_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expense',
            field=models.BooleanField(default=False),
        ),
    ]
